on:        
  push:
    # Pattern matched against refs/tags
    tags:        
      - 'test*'  

name: self-hosted-example

jobs:
  simpleExample:
    runs-on: ubuntu-latest
    steps:
    # checkout branch
    - name: checkout
      uses: actions/checkout@v3
    - name: get commit message
      run: |
        echo ${{ github.event.head_commit.message }}
